const path = require("path");
const fs = require("fs");
const { PurgeCSS } = require("purgecss");
const prettier = require("prettier");
const chokidar = require("chokidar");

/**
 * Gets all HTML|JS files inside a directory or returns a single file if input is a file.
 * @param {string} inputPath - Path to a directory or file.
 * @returns {string[]} - Array of absolute paths to HTML|JS files.
 */
const getHtmlJsFiles = (inputPath) => {
  if (fs.statSync(inputPath).isFile()) {
    return [inputPath]; // Return single file in array format
  }
  return fs.readdirSync(inputPath)
    .filter(file => file.endsWith('.html') || file.endsWith('.js'))
    .map(file => path.join(inputPath, file));
};

/**
 * Purges unused CSS based on HTML content.
 *
 * @param {string} cssFilePath - Path to the CSS file generated by the build.
 * @param {string} inputPath - Path to the HTML file or directory containing HTML files.
 * @param {string} outputCssFilePath - Path to save the purged CSS.
 */
const purgeCss = async (cssFilePath, inputPath, outputCssFilePath) => {
  try {
    if (!fs.existsSync(cssFilePath)) throw new Error("CSS file not found");
    if (!fs.existsSync(inputPath)) throw new Error("HTML file/directory not found");

    console.log("🚀 Purging unused CSS...");

    const htmlFiles = getHtmlJsFiles(inputPath);

    const purgeCSSResult = await new PurgeCSS().purge({
      content: htmlFiles,
      css: [cssFilePath],
      safelist: [
        'active', 'show', 'modal-backdrop', 'collapse',
        'list-group', 'list-group-flush', 'list-group-item',
        'link-muted', 'text-muted', 'border-primary',
        'rounded', 'bg-primary-subtle', 'fs-3', 'fade',
        'tooltip', 'bs-tooltip-auto', 'tooltip-arrow',
        'tooltip-inner', /data-popper-placement.*/,
      ]
    });

    if (!purgeCSSResult || purgeCSSResult.length === 0) {
      throw new Error("PurgeCSS failed to produce results.");
    }

    let purgedCss = purgeCSSResult[0].css;

    console.log("🧹 Removing unnecessary styles...");
    purgedCss = purgedCss.replace(/\/\*[\s\S]*?\*\//g, "");
    purgedCss = purgedCss.replace(/\.cpa-theme :root/g, ".cpa-theme");
    purgedCss = purgedCss.replace(/\.cpa-theme body \{[\s\S]*?\}/gm, "");
    purgedCss = purgedCss.replace(/\s*[^\{\}]+\{\s*\}/g, "");
    purgedCss = purgedCss.replace(/((?:\.\w+[\s.]*)+)\.cpa-theme((?:\s*\.\w+[\s.]*)+)\{/g, ".cpa-theme $1$2{");

    console.log("🎨 Formatting CSS...");
    const formattedCss = await prettier.format(purgedCss, { parser: "css" });

    console.log("💾 Writing purged CSS to output...");
    fs.writeFileSync(outputCssFilePath, formattedCss, "utf8");

    console.log(`✅ Purged CSS written to: ${outputCssFilePath}`);
  } catch (error) {
    console.error("❌ ERROR:", error);
    process.exit(1);
  }
};

/**
 * Watches HTML and JS files for changes and re-runs PurgeCSS.
 * @param {string} cssFilePath - Path to the original CSS file.
 * @param {string} inputPath - Path to the HTML file or directory.
 * @param {string} outputCssFilePath - Path to save the purged CSS.
 */
const watchFiles = (cssFilePath, inputPath, outputCssFilePath) => {
  console.log("👀 Watching for file additions and changes...");

  const watchTarget = fs.statSync(inputPath).isFile() ? inputPath : [cssFilePath, inputPath];
  let watchTimeout;

  chokidar.watch(watchTarget, {
    persistent: true,
    ignoreInitial: false,
    awaitWriteFinish: true,
    usePolling: true,
    interval: 1000,
  })
    .on("add", (filePath) => {
      clearTimeout(watchTimeout);
      watchTimeout = setTimeout(() => {
        if (/\.(html|js)$/i.test(filePath)) {
          console.log(`➕ New file detected: ${filePath}, purging CSS...`);
          purgeCss(cssFilePath, inputPath, outputCssFilePath);
        }
      }, 300);
    })
    .on("change", (filePath) => {
      clearTimeout(watchTimeout);
      watchTimeout = setTimeout(() => {
        if (/\.(html|js)$/i.test(filePath)) {
          console.log(`🔄 Change detected in ${filePath}, purging CSS again...`);
          purgeCss(cssFilePath, inputPath, outputCssFilePath);
        }
      }, 300);
    });
};

module.exports = { purgeCss, watchFiles };
